name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build
        run: |
          set -o pipefail && xcodebuild build \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify --renderer github-actions;
        env:
          SCHEME: FloatingBottomSheet
          SDK: iphonesimulator
          DESTINATION: platform=iOS Simulator,name=iPhone 14 Pro,OS=latest
