name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: macos-14

    env:
      SCHEME: FloatingBottomSheet
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 15,OS=17.2

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_15.2.app
        shell: bash

      - name: Run `build`
        run: |
          set -o pipefail && xcodebuild build \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            | xcbeautify --renderer github-actions
