name: Publish release note
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  pull-requests: read

jobs:
  publish-release-note:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.ref_name }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
