name: Publish release note
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v5
        with:
          version: ${{ github.ref_name }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
